### ISSUE TITLE
Async API crashes when using AirPlay 2

### ISSUE THREAD

**Issue by ntorring** [miracle2k/onkyo-eiscp#109]
My Pioneer SX-S30DAB has just been updated with AirPlay 2 support. But when i power on my receiver from AirPlay, and adjust the volume from my phone, the Receiver thread crashes with the following error:
```Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/eiscp/core.py", line 559, in _thread_loop
    msg = eISCP.get(self, False)
  File "/usr/local/lib/python2.7/dist-packages/eiscp/core.py", line 440, in get
    header = eISCPPacket.parse_header(header_bytes)
  File "/usr/local/lib/python2.7/dist-packages/eiscp/core.py", line 111, in parse_header
    assert magic == 'ISCP'
AssertionError
```

**Comment by zeha** [comment]
Same here, with an Onkyo TX-L20D.
