### ISSUE TITLE
Using a TX-NR696 

### ISSUE THREAD

**Issue by gtrhayrug** [miracle2k/onkyo-eiscp#114]
Hi,

I'm used these features on my previous Onkyo TX-NR636 ... and working fine.
Now, i bought a TX-NR696 but i can't find the correct commands to ask the order.

For example :
- in the 636, my Favorites feature permits to pilot Internet Radio Preset directement using NPR features.... after adding Tunein favorites in My Favorites...
- now for the 696, with no MyFavorites capability, i can't launch preset1, 2 etc from Tunein.

I found the NSV command to pilot the adequate entry...
0E for Tunein, 0A for Spotify...

But when i'm launching...

All other features work perfectly (volume up, down, zone2, main, input selector, status of volume etc)...

`boss@VM-DEB9-JEEDOM:/var/www/html/plugins/script/core/ressources$ onkyo --host 192.168.2.104 NSV0E
Traceback (most recent call last):
  File "/usr/local/bin/onkyo", line 11, in <module>
    load_entry_point('onkyo-eiscp==1.2.7', 'console_scripts', 'onkyo')()
  File "/usr/local/lib/python3.5/dist-packages/onkyo_eiscp-1.2.7-py3.5.egg/eiscp/script.py", line 179, in run
  File "/usr/local/lib/python3.5/dist-packages/onkyo_eiscp-1.2.7-py3.5.egg/eiscp/script.py", line 136, in main
  File "/usr/local/lib/python3.5/dist-packages/onkyo_eiscp-1.2.7-py3.5.egg/eiscp/core.py", line 470, in raw
  File "/usr/local/lib/python3.5/dist-packages/onkyo_eiscp-1.2.7-py3.5.egg/eiscp/core.py", line 270, in filter_for_message
ValueError: Timeout waiting for response.
boss@VM-DEB9-JEEDOM:/var/www/html/plugins/script/core/ressources$ onkyo --host 192.168.2.104 NSV0A
Traceback (most recent call last):
  File "/usr/local/bin/onkyo", line 11, in <module>
    load_entry_point('onkyo-eiscp==1.2.7', 'console_scripts', 'onkyo')()
  File "/usr/local/lib/python3.5/dist-packages/onkyo_eiscp-1.2.7-py3.5.egg/eiscp/script.py", line 179, in run
  File "/usr/local/lib/python3.5/dist-packages/onkyo_eiscp-1.2.7-py3.5.egg/eiscp/script.py", line 136, in main
  File "/usr/local/lib/python3.5/dist-packages/onkyo_eiscp-1.2.7-py3.5.egg/eiscp/core.py", line 470, in raw
  File "/usr/local/lib/python3.5/dist-packages/onkyo_eiscp-1.2.7-py3.5.egg/eiscp/core.py", line 270, in filter_for_message
ValueError: Timeout waiting for response.
boss@VM-DEB9-JEEDOM:/var/www/html/plugins/script/core/ressources$`

Any idea ?

**Comment by nils1976** [comment]
I have the same receiver with the same behavior on the python side....

Did you manage to fix that???

Regards Nils

**Comment by nils1976** [comment]
I found out, that we use the wrong commands....
I will try to ask onkyo, if there is a newer documentation...

**Comment by ChrisRichner** [comment]
I'm facing the same issue with an TX-NR686 Model. I've just started to play around with the script. So maybe I'm just doing something wrong?

`bash-5.0# onkyo -t 192.168.0.16 dock.internet-radio-preset=1
Traceback (most recent call last):
  File "/usr/local/bin/onkyo", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.8/site-packages/eiscp/script.py", line 179, in run
    sys.exit(main() or 0)
  File "/usr/local/lib/python3.8/site-packages/eiscp/script.py", line 136, in main
    response = receiver.raw(iscp_message)
  File "/usr/local/lib/python3.8/site-packages/eiscp/core.py", line 470, in raw
    return filter_for_message(self.get, iscp_message)
  File "/usr/local/lib/python3.8/site-packages/eiscp/core.py", line 270, in filter_for_message
    raise ValueError('Timeout waiting for response.')
ValueError: Timeout waiting for response.`

**Comment by nils1976** [comment]
No I don't think so....I think they changed something in the protocol, which the script doesn't know.
Also the raw commands run into a timeout, I asked onkyo for the eiscp commands to that receiver....but seems to me that they forgot me (which I also did)
Ok so maybe I will asked them again

**Comment by ChrisRichner** [comment]
Hi Nils

That would be great!

Maybe the App https://github.com/mkulesh/onpc reveals how the new onkyo's can be remote controlled?

thank you for your time and effort on this, I really appreciate!

**Comment by nils1976** [comment]
Hi Chris,

Did you installed and tested the software???

**Comment by ChrisRichner** [comment]
By software you mean the mentoned android app?

**Comment by nils1976** [comment]
Right...we only have luck if this software is working with our receivers and is using eiscp.... You are from Swiss? Von meinem Huawei-Tablet gesendet-------- Ursprüngliche Nachricht --------Von: Chris Richner <notifications@github.com>Datum: Sa., 3. Okt. 2020, 10:53An: miracle2k/onkyo-eiscp <onkyo-eiscp@noreply.github.com>Cc: nils1976 <nils@voss-koeln.de>, Comment <comment@noreply.github.com>Betreff: Re: [miracle2k/onkyo-eiscp] Using a TX-NR696  (#114)
By software you mean the mentoned android app?

**Comment by ChrisRichner** [comment]
Yes, I'm Swiss! I'm trying to automate my Onkyo AVR by integrating it into http://homeassistant.io. I'm currently having mixed result by using the sequence as shown http://vtochq-it.blogspot.com/2018/12/onkyo-pioneer-network-remote-control.html.

**Comment by WayeeWang** [comment]
I'm working on the same flow and luckily found this thread. 
For me it works very well with the info from http://vtochq-it.blogspot.com/2018/12/onkyo-pioneer-network-remote-control.html

Chris you are having mixed results most likely because you didn't put delays enough between steps. 
Also, the last two steps (i.e. performing selections), I need to use "NLSL0" to select Presets, and "NLSL5" to select the 6th preset. "NLSI***" for selecting index, as used in that tutorial, does not work well for me.

Hope this helps you out.
