### ISSUE TITLE
problem importing netifaces 

### ISSUE THREAD

**Issue by Enigma3000** [miracle2k/onkyo-eiscp#119]
Hi, I can't make the script work in Kodi. Apparently, it can't find netifaces although it's installed with onkyo-eiscp. I tried Python3 32 bit and 64 bit. No luck.

Any help is highly appreciated.

`   Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named netifaces
                                            Traceback (most recent call last):
                                              File "C:\python\Lib\site-packages\volumedown.py", line 1, in <module>
                                                import eiscp
                                              File "C:\python\Lib\site-packages\eiscp\__init__.py", line 6, in <module>
                                                from .core import eISCP
                                              File "C:\python\Lib\site-packages\eiscp\core.py", line 10, in <module>
                                                import netifaces
                                            ImportError: No module named netifaces
                                            -->End of Python script error report<--`

**Comment by cracket** [comment]
I have similar problem, @Enigma3000  have you found a solution?
