### ISSUE TITLE
UnicodeEncodeError when trying to display help zone2 volume

### ISSUE THREAD

**Issue by apok** [miracle2k/onkyo-eiscp#12]
~/onkyo-eiscp$ onkyo --help-commands zone2 volume
Possible values for this command:
Traceback (most recent call last):
  File "/usr/local/bin/onkyo", line 9, in <module>
    load_entry_point('onkyo-eiscp==0.9.1', 'console_scripts', 'onkyo')()
  File "/usr/local/lib/python2.7/dist-packages/onkyo_eiscp-0.9.1-py2.7.egg/eiscp/script.py", line 129, in run
    sys.exit(main() or 0)
  File "/usr/local/lib/python2.7/dist-packages/onkyo_eiscp-0.9.1-py2.7.egg/eiscp/script.py", line 85, in main
    print '  %s - %s' % (value['name'], value['description'])
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 24: ordinal not in range(128)

**Comment by miracle2k** [comment]
This is probably an issue with locale configuration. Does the Terminal not support Unicode?

What does:

   $ python
   >>> import locale
   >>> locale.getdefaultlocale()[1]

say?

**Comment by miracle2k** [comment]
It is probably something to fixed in this lib, e.g.:

https://pythonhosted.org/kitchen/unicode-frustrations.html#frustration-3-inconsistent-treatment-of-output
