### ISSUE TITLE
ValueError: Timeout waiting for response. 

### ISSUE THREAD

**Issue by bassmint** [miracle2k/onkyo-eiscp#13]
It used to work. Now it does not.
All commands sent gget same response.

-input
macbook:~ sysop$ onkyo main.system-power:standby

-response
<eISCP(TX-8050) 192.168.1.202:60128>: PWR00
Traceback (most recent call last):
  File "/usr/local/bin/onkyo", line 8, in <module>
    load_entry_point('onkyo-eiscp==0.9.1', 'console_scripts', 'onkyo')()
  File "build/bdist.macosx-10.9-intel/egg/eiscp/script.py", line 129, in run
  File "build/bdist.macosx-10.9-intel/egg/eiscp/script.py", line 122, in main
  File "build/bdist.macosx-10.9-intel/egg/eiscp/core.py", line 391, in raw
  File "build/bdist.macosx-10.9-intel/egg/eiscp/core.py", line 251, in filter_for_message
ValueError: Timeout waiting for response.

**Comment by guikubivan** [comment]
Anybody have an update on this? It's breaking all the cool functionality I had programmed based on responses from the receiver.

**Comment by FredFrancisIT** [comment]
:-( Same error here !

**Comment by zwada** [comment]
Same error

**Comment by mikerodrigues** [comment]
Can you control your stereo from other clients? Like the Onkyo Android app? It could be your receiver. 

I installed onkyo-eiscp with pip and it works fine for me.

    pip show onkyo-eiscp
---
Name: onkyo-eiscp
Version: 0.9.1
Location: /usr/local/lib/python2.7/dist-packages/onkyo_eiscp-0.9.1-py2.7.egg
Requires: docopt

**Comment by basheuer** [comment]
Getting the same error here

**Comment by mikerodrigues** [comment]
Have you power cycled your receiver?

**Comment by basheuer** [comment]
@mikerodrigues just tried, without success:

```PS C:\Python27\Scripts> .\onkyo.exe SLI2B NTCSELECT NTCUP
<eISCP(TX-NR509) 192.168.1.10:60128>: SLI2B
SLI2B
<eISCP(TX-NR509) 192.168.1.10:60128>: NTCSELECT
Traceback (most recent call last):
  File "C:\Python27\Scripts\onkyo-script.py", line 9, in <module>
    load_entry_point('onkyo-eiscp==0.9.1', 'console_scripts', 'onkyo')()
  File "build\bdist.win-amd64\egg\eiscp\script.py", line 129, in run
  File "build\bdist.win-amd64\egg\eiscp\script.py", line 122, in main
  File "build\bdist.win-amd64\egg\eiscp\core.py", line 391, in raw
  File "build\bdist.win-amd64\egg\eiscp\core.py", line 251, in filter_for_message
ValueError: Timeout waiting for response.
PS C:\Python27\Scripts>
```

**Comment by Crille1** [comment]
Hello, had this problem and a hard reboot (AC cable out ad in) solved my problem.

**Comment by miracle2k** [comment]
FWIW, I had to power cycle myself.
