### ISSUE TITLE
Timeout waiting for response with speaker-level-calibration

### ISSUE THREAD

**Issue by cgagliardi** [miracle2k/onkyo-eiscp#14]
The speaker-level-calibration commands (ie SLC) don't seem to work with onkyo-eiscp.  When using this series of commands:
`onkyo speaker-level-calibration:chsel speaker-level-calibration:up speaker-level-calibration:up`

I get this error:
`<eISCP(HT-RC460) 192.168.2.56:60128>: SLCCHSEL
Traceback (most recent call last):
  File "/usr/local/bin/onkyo", line 9, in <module>
    load_entry_point('onkyo-eiscp==0.9.1', 'console_scripts', 'onkyo')()
  File "/usr/local/lib/python2.7/dist-packages/onkyo_eiscp-0.9.1-py2.7.egg/eiscp/script.py", line 131, in run
    sys.exit(main() or 0)
  File "/usr/local/lib/python2.7/dist-packages/onkyo_eiscp-0.9.1-py2.7.egg/eiscp/script.py", line 123, in main
    response = receiver.raw(iscp_command)
  File "/usr/local/lib/python2.7/dist-packages/onkyo_eiscp-0.9.1-py2.7.egg/eiscp/core.py", line 391, in raw
    return filter_for_message(self.get, iscp_message)
  File "/usr/local/lib/python2.7/dist-packages/onkyo_eiscp-0.9.1-py2.7.egg/eiscp/core.py", line 251, in filter_for_message
    raise ValueError('Timeout waiting for response.')
ValueError: Timeout waiting for response.`

The first command clearly goes through.  I can see the receiver show the level for the front left speaker, but the up and down commands have no affect.  It seems like this command specifically expects a stream of commands and eiscp doesn't handle that use case.

I found [this thread](http://www.avsforum.com/t/1399728/iscp-for-avr-setup) which shows an example of using SLC where a series of several select, up, and down commands are sent to get the desired effect.

**Comment by mattpurnell** [comment]
I have the same experience. I think you just have to send the command without waiting for a response, and then use either up or down within a few seconds afterward.

I am integrating my stereo with Home Assistant, and my biggest issue is that I do not get any state information from the stereo.. e.g. current channel or that channel's level. So I cannot do anything channelwise, without being close enough to read the little Onkyo screen.
