### ISSUE TITLE
getting error to run onkyo

### ISSUE THREAD

**Issue by toshibochan** [miracle2k/onkyo-eiscp#39]
onkyo -- discover 

Traceback (most recent call last):
  File "/usr/local/bin/onkyo", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: netifaces

**Comment by toshibochan** [comment]
i run "sudo pip install only-eiscp"
this installation is on my raspberry pi and give me this error when i run "onkyo --discover". but i did same installation on my mac and work okay. 

please help

**Comment by toshibochan** [comment]
oh look like the netifaces directory is missing!!!!

**Comment by miracle2k** [comment]
Try "pip install netifaces".

**Comment by iisquazar** [comment]
For me to get this working on a fresh Jessie inslall I had t follow the following steps:
sudo apt-get install python-setuptools
**sudo apt-get install -t jessie python-dev**
easy_install https://github.com/miracle2k/onkyo-eiscp/tarball/master

(suggestion from leader21 @ primatic.org)
maybe good to add this to the instructions?
