### ISSUE TITLE
Trouble getting volume state

### ISSUE THREAD

**Issue by maleadt** [miracle2k/onkyo-eiscp#57]
I'm having some trouble querying the current volume state.
Works fine for the main zone, using the `query` command:

```
$ onkyo volume.query 
TX-NR545: volume = 22
```

But fails when specifying a zone (which I need for zone 2, I presume):

```
$ onkyo main.volume.query
Traceback (most recent call last):
  File ".local/bin/onkyo", line 11, in <module>
    load_entry_point('onkyo-eiscp==1.0', 'console_scripts', 'onkyo')()
  File ".local/lib/python3.6/site-packages/eiscp/script.py", line 179, in run
    sys.exit(main() or 0)
  File ".local/lib/python3.6/site-packages/eiscp/script.py", line 132, in main
    iscp_message = command_to_iscp(command)
  File ".local/lib/python3.6/site-packages/eiscp/core.py", line 203, in command_to_iscp
    argument = arguments[0]
IndexError: list index out of range

$ onkyo zone2.volume.query
IndexError: list index out of range
```

Using the API, a different error seems to happen:

```
> receiver.command('volume', 'query', zone='main')
Traceback (most recent call last):
  File ".local/lib/python3.6/site-packages/eiscp/core.py", line 207, in command_to_iscp
    value = commands.VALUE_MAPPINGS[group][prefix][argument]
KeyError: 'q'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./volume.py", line 8, in <module>
    receiver.command('volume', 'query', zone='main')
  File ".local/lib/python3.6/site-packages/eiscp/core.py", line 465, in command
    iscp_message = command_to_iscp(command, arguments, zone)
  File ".local/lib/python3.6/site-packages/eiscp/core.py", line 221, in command_to_iscp
    '"{}" in zone "{}"'.format(argument, command, zone))
ValueError: "q" is not a valid argument for command "volume" in zone "main"
```

Am I doing something wrong? Seems to work fine using raw commands:

```
$ onkyo MVLQSTN
TX-NR545: MVL16
$ onkyo ZVLQSTN
TX-NR545: ZVL0A
```

Tested using latest master, on Python 3.6 (Arch Linux).

**Comment by toshibochan** [comment]
try
onkyo main.volume=query
onkyo system-power=on or standby
onkyo main.volume=22
onkyo zone2.volume=query
onkyo zone2.power=on  or standby
onkyo zone2.volume=22

**Comment by toshibochan** [comment]
main, zone2, 3, 4 power have to be on for volume to work.
onkyo system-power=on
onkyo main.volume=22
or
onkyo zone2.power=on
onkyo zone2.volume=22

**Comment by maleadt** [comment]
Oh I see, the valid syntax is `volume=query`. That works for the CLI interface. The API still errors out when using the more explicit syntax though, eg:

```
receiver.command('volume', 'query', zone='main')

Traceback (most recent call last):
  File "eiscp/core.py", line 207, in command_to_iscp
    value = commands.VALUE_MAPPINGS[group][prefix][argument]
KeyError: 'q'
```

**Comment by Woetsel** [comment]
In a python script I got it working by using:

    receiver.command('volume', arguments=['query'], zone='main')

That worked for me.
