### ISSUE TITLE
After updates get a lot is not a valid command in zone "main"

### ISSUE THREAD

**Issue by moskovskiy82** [miracle2k/onkyo-eiscp#74]
After some recent update (can't tell exactly then) the following command stopped working (was working fine before)

onkyo -n709 internet-radio-preset=2
Error: "internet-radio-preset" is not a valid command in zone "main"

**Comment by miracle2k** [comment]
Are you sure? Which version is that? Make sure it's the lastest one. I just tried it and the command seems to work.

**Comment by miracle2k** [comment]
Actually, strike that. I can reproduce it.

**Comment by miracle2k** [comment]
This was broken in 94d7c42a0ff1bf286ee16c4cc2bb102b0ec3ed5e. 

Reason is that in the Onkyo Excel file, this and a handful of other commands where moved to a new tab.

**Comment by moskovskiy82** [comment]
So any chances that the fix will make iit into a new release?

And as a workaround - will it be enough to copy the necessary command lines into the main section of commands.py? Will that work?

**Comment by miracle2k** [comment]
I don't know when I find the time to actually fix the import. One option is to add the command manually to the eiscp-commands.yaml file (not commands.py).

Another one is to issue the ``NPR`` command (I think that's the one) manually:

Something like this maybe

``onkyo -n709 NPR2``

**Comment by moskovskiy82** [comment]
Where can i find that file? 

Installed 1.24 along side outside virtual enviroment via easy_install. 

Running 
```
/usr/local/bin/onkyo -n709 internet-radio-preset=4
still gives
('Error:', ValueError('"internet-radio-preset" is not a valid command in zone "main"',))
```

Running 

```
$ /usr/local/bin/onkyo -n709 NPR4
Traceback (most recent call last):
  File "/usr/local/bin/onkyo", line 11, in <module>
    load_entry_point('onkyo-eiscp==1.2.4', 'console_scripts', 'onkyo')()
  File "build/bdist.linux-armv7l/egg/eiscp/script.py", line 179, in run
  File "build/bdist.linux-armv7l/egg/eiscp/script.py", line 136, in main
  File "build/bdist.linux-armv7l/egg/eiscp/core.py", line 463, in raw
  File "build/bdist.linux-armv7l/egg/eiscp/core.py", line 270, in filter_for_message
ValueError: Timeout waiting for response.
```

`And $ sudo find /* -name "*eiscp-commands.yaml*"`

Produces no result

**Comment by moskovskiy82** [comment]
Sorry to bug - but maybe some other workaround possible?

**Comment by unixgeex** [comment]
Same here NPR command not working.

```
$ onkyo --host 192.168.x.x --port 60128 NPR05

Traceback (most recent call last):
  File "/usr/local/bin/onkyo", line 9, in <module>
    load_entry_point('onkyo-eiscp==1.2.4', 'console_scripts', 'onkyo')()
  File "/usr/local/lib/python2.7/dist-packages/onkyo_eiscp-1.2.4-py2.7.egg/eiscp/script.py", line 179, in run
  File "/usr/local/lib/python2.7/dist-packages/onkyo_eiscp-1.2.4-py2.7.egg/eiscp/script.py", line 136, in main
  File "/usr/local/lib/python2.7/dist-packages/onkyo_eiscp-1.2.4-py2.7.egg/eiscp/core.py", line 463, in raw
  File "/usr/local/lib/python2.7/dist-packages/onkyo_eiscp-1.2.4-py2.7.egg/eiscp/core.py", line 270, in filter_for_message
ValueError: Timeout waiting for response.
```
Please help.

**Comment by unixgeex** [comment]
Figured out something until NPR/NPZ are fixed ...
Just do whatever action sequence to get the internet radio to play. For preset4 (down key three times on the root menu) :  
`onkyo --host 192.168.x.x --port 60128 SLI28 NTCRETURN NTCRETURN NTCRETURN NTCDOWN NTCDOWN NTCDOWN NTCSELECT NTCSELECT`
Not neat ... but works for me.

**Comment by R1chardTM** [comment]
I can't seem to get setting an internet radio preset working either.

**Comment by ErikMinekus** [comment]
I simply moved everything from the "dock" zone to the "main" zone and regenerated commands.py, which fixes the issue for now. [Download here](https://puu.sh/zc6zo/4d0325c3a8.py).

**Comment by tpetri** [comment]
Hi, any chance this could be looked at at some point?

**Comment by Fidelity88** [comment]
+1!

**Comment by unixgeex** [comment]
Sorry to bug, is going to be look at ?
