### ISSUE TITLE
Error: ValueError: Timeout waiting for response.

### ISSUE THREAD

**Issue by ouija** [miracle2k/onkyo-eiscp#83]
When running any command, such as onkyo volume=5, I am now getting the following error:

`Traceback (most recent call last):
  File "/opt/bin/onkyo", line 11, in <module>
    load_entry_point('onkyo-eiscp==1.2.4', 'console_scripts', 'onkyo')()
  File "/opt/lib/python2.7/site-packages/eiscp/script.py", line 179, in run
    sys.exit(main() or 0)
  File "/opt/lib/python2.7/site-packages/eiscp/script.py", line 136, in main
    response = receiver.raw(iscp_message)
  File "/opt/lib/python2.7/site-packages/eiscp/core.py", line 463, in raw
    return filter_for_message(self.get, iscp_message)
  File "/opt/lib/python2.7/site-packages/eiscp/core.py", line 270, in filter_for_message
    raise ValueError('Timeout waiting for response.')
ValueError: Timeout waiting for response.
`

Which I wasn't when I first tried out this script a few days ago, and in that time I had to reinstall Python due to some issue, and am not sure what has caused this problem.  Any help is appreciated.

Note that using the discovery command works and finds the receiver without issues..

**Comment by ouija** [comment]
Nevermind, I'm an idiot and didn't find another issue regarding this same problem (https://github.com/miracle2k/onkyo-eiscp/issues/13).

Unplugging the AC from the unit, holding power for 15 sec while unplugged, and plugging back in resolved the issue.   Damn thing.. :)
