### ISSUE TITLE
socket.error: [Errno 111] Connection refuse

### ISSUE THREAD

**Issue by antipiot** [miracle2k/onkyo-eiscp#94]
HI!

I'm having an issue:
The script works very well for a while (1 to 3 days) then stop responding to commands:

`pi@raspberrypi:~ $ onkyo -n -S30DAB system-power=on
Traceback (most recent call last):
  File "/usr/local/bin/onkyo", line 11, in <module>
    load_entry_point('onkyo-eiscp==1.2.4', 'console_scripts', 'onkyo')()
  File "/usr/local/lib/python2.7/dist-packages/onkyo_eiscp-1.2.4-py2.7.egg/eiscp/script.py", line 179, in run
  File "/usr/local/lib/python2.7/dist-packages/onkyo_eiscp-1.2.4-py2.7.egg/eiscp/script.py", line 120, in main
  File "/usr/local/lib/python2.7/dist-packages/onkyo_eiscp-1.2.4-py2.7.egg/eiscp/core.py", line 413, in __enter__
  File "/usr/local/lib/python2.7/dist-packages/onkyo_eiscp-1.2.4-py2.7.egg/eiscp/core.py", line 402, in _ensure_socket_connected
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refuse`

Turning it on then off does not solve the problem, only thing i can do is to unplug it then replug it to main then the commands works again for a while. Any hints?

**Comment by antipiot** [comment]
Nobody to help me getting rid of thoses socket timeout?

Isn't there anyway to force close or maintain connexion? 
Anything that helps will really be appreciated as everything works perfectly appart from thoses deconnexions.
